<?php
	#Menu
?>
<form>
<div>
	<i class="fa fa-bars toggle_menu opacity_one"></i>
	<div class="sidebar_menu hide_menu">
		<i class="fa fa-times"></i>
		<center>
			<a href="index.php"><img src="images/logo_lg.png" class="sidebar_header boxed_item_nosides"></a>
			<h2 class="logo_title">Data Scientist and <br/><span class="logo_bold">Public Health Nerd</span></h2>
		</center>
		<ul class="navigation_section">
			<li id="profile"><a href="index.php">ABOUT ME</a></li>
			<li id="education"><a href="education.php">EDUCATION</a> </li>
         	        <li id="work_experience"> <a href="work_history.php">WORK HISTORY</a> </li>
                	<li id="portfolio"> <a href="portfolio.php">PORTFOLIO </a> </li>
                	<li id="skills"><a href="skills.php"> SKILLS</a> </li>
		</ul>
	</div>
</div>
</form>
